Fixed white bar at smaller widths
LondonKPC/lkpc-frontend pull request #57
Opened 2024-12-28 19:43 UTC by Lunchii

Closes #53 
## Overview
The text from the footer component made the screen stretch due to the big font size.
Changed the text so that it changes for mobile and is now viewable

2024-12-28 22:52 UTC, Cheekane requested changes
@Lunchii Get rid of useless images.

2024-12-28 22:52 UTC, Cheekane commented on app/home/page.tsx
> +>>>>>>> Stashed changes
Fix this.

2024-12-28 23:54 UTC, jerpyk reviewed
👍
<img width="387" alt="Screenshot 2024-12-28 at 6 53 25 PM" src="https://github.com/user-attachments/assets/1aaa1eb3-3c9c-4992-bf75-b78a5b543cde" />

2024-12-29 01:50 UTC, ZestyScrubz approved these changes
Good Job, but it still breaks on very small screen, but that's no problem

2024-12-29 03:09 UTC, Cheekane approved these changes
🦖

2024-12-29 03:16 UTC, merged