Contact page
LondonKPC/lkpc-frontend pull request #58
Opened 2024-12-28 23:44 UTC by Lunchii

Closes #49 
## Overview
Created placeholder image, designed the basic layout, added some styles.
Changed the z-index on the navigation bar so it should stay on top of all objects or components.
Currently not 100% completed but **requires contact info** and **an image**

2024-12-29 02:48 UTC, jerpyk reviewed
about page looks good, more needed to contact page

2024-12-29 03:08 UTC, Cheekane requested changes
@Lunchii 
Doesn't work. Its fine for now, we need to figure out the react router stuff.
Also dont add capy images or random images, we are going to present it later, so keep images/background to default colors.

2024-12-29 03:08 UTC, Cheekane commented on app/contact/page.tsx
> +function Contact() {
```suggestion
const Contact = () => {
```

2024-12-30 14:05 UTC, Cheekane requested changes
Not bad, but here are some things to do:
1. Lets actually design the contacts page on canvas first.
2. Make things that are reusable into components.

2025-01-01 01:09 UTC, closed without merging